### PR TITLE
Fix ExecutionEngineException and add test

### LINKED ISSUE #53: ExecutionEngineException in diagnostic source listener
You can cause the CLR to crash by using an invalid combination of types.

```
new { bar = new Guid() }

...

[DiagnosticName(...)]
public void OnFoo (string bar)
{
    ...
}
```

This is not valid, but the failure mode should be throwing an exception explaining the mistake, not shutting down the CLR 😆 

------------

The issue here is that the generated thunk for *splatting* the type isn't doing the right thing when the result of accessing the `anonymoustype<>.bar` property is a value type.

Adding the following at ProxyMethodEmitter@L160 fixing the issue

```
if (mapping.PropertyType.GetTypeInfo().IsValueType)
{
    il.Emit(OpCodes.Box, mapping.PropertyType);
}
```

Additionally, we should see if we can do anything to surface errors about this **with context** as it is today when you fix the bug, the exception message you get doesn't mention the method on the adapter which caused the problem.

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes #53.

### CODE REVIEW

File: src/Microsoft.Extensions.DiagnosticAdapter/Internal/ProxyMethodEmitter.cs [hunk 1]
```diff
@@ -157,7 +157,10 @@ private static PropertyInfo[] GetPropertyToParameterMappings(Type inputType, Par
                         il.Emit(OpCodes.Ldarg_1); // The event-data
                         il.Emit(OpCodes.Castclass, inputType);
                         il.Emit(OpCodes.Callvirt, mapping.GetMethod);
-
+                        if (mapping.PropertyType.GetTypeInfo().IsValueType)
```
Comment (rynowak) [inline src/Microsoft.Extensions.DiagnosticAdapter/Internal/ProxyMethodEmitter.cs]: It wouldn't hurt to explain this with a comment

File: test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs [hunk 2]
```diff
@@ -79,6 +90,19 @@ public void IsEnabled_FalseForNonenlistedEvent()
         }
 
         [Fact]
+        public void CallingWriteWithWrongTypeThrows()
```
Comment (rynowak) [inline test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs]: Really the detail here is that it's not just the 'wrong type' it's that it's a value type and we try to create a proxy for it.

I suspect we could benefit from beefing up our tests around value types.

Comment (ryanbrandenburg) [inline test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs]: While we're on it, if I do
```
[DiagnosticName("Bar")]
public void OnBar(int baz)
{
    ...
}
...
adapter.Write("Bar", new { baz = (int?)null });
```
We would expect that to throw right? Because the actual behavior is that it calls OnBar with baz=0.

File: test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs [hunk 3]
```diff
@@ -79,6 +96,47 @@ public void IsEnabled_FalseForNonenlistedEvent()
...
 
         [Fact]
+        public void CallingWriteWithNullForNonNullableThrows()
+        {
+            // Arrange
+            var target = new Crash();
+            var adapter = CreateAdapter(target);
+            int? x = null;
+            int y = (int)x;
+            Console.WriteLine(y);
```
Comment (ajaybhargavb) [inline test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs]: Remove

File: test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs [hunk 4]
```diff
@@ -79,6 +96,47 @@ public void IsEnabled_FalseForNonenlistedEvent()
...
+            // Act & Assert
+            Assert.Equal(0, target.CallCount);
+            Assert.Throws<InvalidOperationException>(() => adapter.Write("Bar", new { baz = (int?)null }));
+            Assert.Equal(0, target.CallCount);
+        }
+
+        [Fact]
+        public void CallingWriteWithUnboxableThrows()
```
Comment (ajaybhargavb) [inline test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs]: Rename this method? Unboxable seems confusing.

File: test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs [hunk 5]
```diff
@@ -79,6 +96,47 @@ public void IsEnabled_FalseForNonenlistedEvent()
...
+        [Fact]
+        public void CallingWriteWithProxyTypeThrows()
+        {
+            // Arrange
+            var target = new Crash();
+            var adapter = CreateAdapter(target);
+
+            // Act & Assert
+            Assert.Equal(0, target.CallCount);
+            Assert.Throws<InvalidOperationException>(() => adapter.Write("Foo", new { bar = new Guid() }));
```
Comment (ajaybhargavb) [inline test/Microsoft.Extensions.DiagnosticAdapter.Test/DiagnosticSourceAdapterTest.cs]: Is it worth verifying the exception message?

File: src/Microsoft.Extensions.DiagnosticAdapter/Internal/ProxyMethodEmitter.cs [hunk 6]
```diff
@@ -158,6 +158,11 @@ private static PropertyInfo[] GetPropertyToParameterMappings(Type inputType, Par
                         il.Emit(OpCodes.Castclass, inputType);
                         il.Emit(OpCodes.Callvirt, mapping.GetMethod);
 
+                        // If we have a value type box it to the target type.
+                        if (mapping.PropertyType.GetTypeInfo().IsValueType)
+                        {
+                            il.Emit(OpCodes.Box, mapping.PropertyType);
+                        }
```
Comment (ajaybhargavb) [inline src/Microsoft.Extensions.DiagnosticAdapter/Internal/ProxyMethodEmitter.cs]: nit: Add blank line below this

**Comment by ryanbrandenburg** [comment]
:up::date:
